city=['Moravian Falls', 'Orient', 'Malad City', 'Boulder', 'Doe Hill',
       'Dublin', 'Holcomb', 'Edinburg', 'Manor', 'Clarksville',
       'Clarinda', 'Shenandoah Junction', 'Saint Petersburg', 'Grenada',
       'High Rolls Mountain Park', 'Harrington Park', 'Lahoma',
       'Carlisle', 'Harborcreek', 'Elizabeth', 'Methuen', 'Moulton',
       'Plainfield', 'May', 'Waukesha', 'Bailey', 'Romulus', 'Freedom',
       'Honokaa', 'Valentine', 'Westfir', 'Tiptonville', 'Republic',
       'Baton Rouge', 'Washington', 'Big Creek', 'Bellmore', 'Florence',
       'Allentown', 'Moriches', 'Esbon', 'Chatham', 'Thompson',
       'North Prairie', 'Laredo', 'Grant', 'Conway', 'New Goshen',
       'Sunflower', 'Enola', 'Roosevelt', 'Pointe Aux Pins', 'Dallas',
       'Jay', 'North Tonawanda', 'Athena', 'Chester', 'Elkhart',
       'Surrency', 'Arcadia', 'Gaithersburg', 'Bowdoin', 'Heart Butte',
       'San Jose', 'Rumely', 'Cranks', 'Ravenna', 'Utica', 'Uledi',
       'Naples', 'Thida', 'Parks', 'Central', 'Fort Washakie', 'Etlan',
       'Brinson', 'Shrewsbury', 'Bigelow', 'North Washington', 'Holloway',
       'Littleton', 'Hinesburg', 'Meadville', 'Elberta', 'Moab',
       'Diamond', 'Bradley', 'Hopewell', 'Hawthorne', 'Kensington',
       'Ruth', 'Avoca', 'Princeton', 'Sherman', 'Loxahatchee',
       'Smackover', 'Cokeburg', 'Leetsdale', 'Manville',
       'Westhampton Beach', 'New York City', 'Halstad', 'Allenhurst',
       'June Lake', 'Sixes', 'Holstein', 'Brantley', 'Paxton',
       'Westerville', 'Timberville', 'Dunlevy', 'Coyle', 'Elizabethtown',
       'Garrattsville', 'Lomax', 'Egan', 'Brownville', 'Drakes Branch',
       'Ballwin', 'Fields Landing', 'West Palm Beach', 'West Chazy',
       'Lebanon', 'Jones', 'Burke', 'Webster City', 'Ozawkie',
       'Blackville', 'Damascus', 'Sea Island', 'Rule', 'Jefferson',
       'Huntsville', 'Hinckley', 'Acworth', 'Camden', 'Smiths Grove',
       'Philadelphia', 'Murrayville', 'Melbourne', 'Palmyra', 'Jermyn',
       'Belfast', 'West Sayville', 'Sturgis', 'Lohrville', 'Arlington',
       'Saint Paul', 'Girard', 'Fairview', 'Farmington', 'Kilgore',
       'Springfield', 'Lepanto', 'Karnack', 'Louisiana', 'Kansas City',
       'Mesa', 'Pomona', 'Lonetree', 'Port Saint Lucie', 'Centerview',
       'Colorado Springs', 'Easton', 'West Columbia', 'Maysville',
       'Muskegon', 'Johns Island', 'Metairie', 'Blairsden-Graeagle',
       'Hampton', 'Viola', 'Paulding', 'Sontag', 'Clutier', 'Reno',
       'Barnstable', 'Cardwell', 'Kingsford Heights', 'Phoenix',
       'Newhall', 'Norwalk', 'Mc Nabb', 'Tulsa', 'Barnard', 'San Antonio',
       'Bridger', 'Tomales', 'Mallie', 'Oxford', 'Turner', 'Eureka',
       'Marietta', 'Redford', 'Weeping Water', 'Waynesfield', 'Portland',
       'Greenwood', 'Boonton', 'Murfreesboro', 'Warren', 'Meridian',
       'Cherokee Village', 'Bristow', 'Ash Flat', 'Iliff', 'Deadwood',
       'Burlington', 'Wales', 'Churubusco', 'Afton', 'Cochranton',
       'Mound City', 'West Harrison', 'Pembroke Township', 'Joliet',
       'Fulton', 'Saint Bonaventure', 'Keisterville', 'Greenview',
       'Lakeport', 'Rock Tavern', 'Llano', 'Altair', 'Harrodsburg',
       'Carlotta', 'Wittenberg', 'Des Moines', 'Auburn', 'Dadeville',
       'Wilton', 'Ollie', 'Mifflin', 'Amsterdam', 'Manderson', 'Holliday',
       'Dumont', 'Payson', 'Birmingham', 'Creola', 'Texarkana',
       'Fullerton', 'Ruckersville', 'Blooming Grove', 'Comfort',
       'Louisville', 'Atglen', 'North Loup', 'Grassflat', 'Mill Creek',
       'Moores Hill', 'Browning', 'Smithfield', 'Cromona', 'Kent',
       'Harwood', 'Delhi', 'Gadsden', 'Brooklin', 'Bay Minette',
       'Higganum', 'Ashfield', 'Fiddletown', 'Andrews',
       'Huntington Beach', 'Westport', 'Comfrey', 'Heidelberg', 'Powell',
       'De Witt', 'Howes Cave', 'Oolitic', 'Belmond', 'Mooresville',
       'Steuben', 'Armagh', 'Edisto Island', 'Marathon', 'Port Gibson',
       'Brandon', 'Tallmansville', 'Glendale', 'El Paso', 'Lamberton',
       'Manchester', 'Emporium', 'Alva', 'Roma', 'Prairie Hill',
       'Blairstown', 'Bridgeport', 'Grand Junction', 'Tamaroa',
       'Great Mills', 'Laguna Hills', 'West Decatur', 'Aledo', 'Pelham',
       'Albuquerque', 'Scotland', 'Azusa', 'Lanark Village',
       'Cuyahoga Falls', 'Manistique', 'Mountain Park', 'University',
       'Breesport', 'Harper', 'Bagley', 'Fenelton', 'Gardiner',
       'Greendale', 'Bay City', 'Minneapolis', 'Gregory', 'Tuscarora',
       'Northport', 'Rock Springs', 'Altona', 'Paauilo', 'Ratcliff',
       'Mount Morris', 'Pembroke', 'Pittsburgh', 'West Henrietta',
       'Tickfaw', 'Rhame', 'Eugene', 'Seneca', 'Daly City', 'Logan',
       'Coleman', 'Norman', 'Cape Coral', 'Summerfield', 'Daniels',
       'Tampa', 'Gainesville', 'East Canaan', 'Dresden', 'Luzerne',
       'Parkers Lake', 'Olmsted', 'Mendon', 'Fayetteville', 'Notrees',
       'Pecos', 'Brunson', 'Belgrade', 'Kenner', 'Stillwater', 'Cadiz',
       'Avera', 'Annapolis', 'Powell Butte', 'Rosewood', 'Lima', 'Thrall',
       'Union', 'Riverview', 'Hannawa Falls', 'Cazenovia', 'North Judson',
       'Fordoche', 'Bauxite', 'Cisco', 'Apison', 'Cass', 'Santa Monica',
       'Amorita', 'Laramie', 'Hudson', 'Center Point', 'Lagrange',
       'Dexter', 'Brainard', 'Winger', 'Thomas', 'Shelter Island',
       'Tupper Lake', 'Humboldt', 'Winter', 'Corona', 'Lakeland',
       'Vienna', 'Goreville', 'Yellowstone National Park', 'Shedd',
       'Wilmington', 'Mc Cracken', 'Milner', 'Noonan', 'Falconer',
       'Desdemona', 'Bethel Springs', 'Burns Flat', 'Glen Rock', 'Basye',
       'Lowville', 'Du Pont', 'Burrton', 'Lubbock', 'Independence',
       'Creedmoor', 'Wichita', 'Houston', 'Clay Center', 'Sebring',
       'Whittemore', 'Ogdensburg', 'Spearsville', 'Oaks',
       'Paradise Valley', 'Burbank', 'New Holstein', 'Schaefferstown',
       'Washington Court House', 'Eldridge', 'San Diego', 'Marienville',
       'Fort Myers', 'Kissee Mills', 'Bronx', 'Montandon', 'Espanola',
       'Campbell', 'Indian Wells', 'Hewitt', 'Leo', 'Mulberry Grove',
       'Mountain Center', 'Helm', 'Detroit', 'Moundsville', 'Falmouth',
       'Zaleski', 'Lowell', 'Henderson', 'Corsica', 'Wilmette',
       'Mayersville', 'Pearlington', 'Cleveland', 'Whigham', 'Kirby',
       'Knoxville', 'Highland', 'Hazel', 'Alexandria', 'Port Ewen',
       'Lamy', 'Mount Clemens', 'North Wilkesboro', 'Morrisdale', 'Cord',
       'Sauk Rapids', 'Center Tuftonboro', 'Hatch', 'Margaretville',
       'Goodrich', 'Ford', 'South Londonderry', 'Cross Plains',
       'Lake Jackson', 'Orangeburg', 'Walnut Ridge', 'Tower Hill',
       'Oakland', 'Montrose', 'Parker Dam', 'Rocky Mount', 'Coleharbor',
       'Falls City', 'Moriarty', 'Southfield', 'Glade Spring', 'Slayden',
       'O Brien', 'Bristol', 'Umatilla', 'Hooper', 'Saint Amant',
       'Clayton', 'Cascade Locks', 'Saint James City', 'Vinton',
       'Christine', 'Alder', 'Roseland', 'Tyaskin', 'Lake Oswego',
       'Parker', 'Wauchula', 'Colton', 'Juliette', 'River',
       'Beaver Falls', 'Elk Rapids', 'Lonsdale', 'West Hartford',
       'Kirtland Afb', 'Shields', 'Riverton', 'Whaleyville', 'Sacramento',
       'Marion', 'Adams', 'Zavalla', 'Cottekill', 'Shippingport',
       'Montgomery', 'Sun City', 'Grover', 'Newport',
       'South Richmond Hill', 'Parsonsfield', 'Garfield', 'Jelm',
       'Meredith', 'Battle Creek', 'Woodville', 'Luray', 'Cowlesville',
       'Haw River', 'Falls Church', 'Topeka', 'Haynes', 'Grimesland',
       'Smith River', 'Moorhead', 'White Sulphur Springs', 'East Andover',
       'Superior', 'Hurricane', 'Bowersville', 'Mount Saint Joseph',
       'Hancock', 'Dubre', 'Collettsville', 'Rossville', 'Red River',
       'Benton', 'Monmouth Beach', 'Bessemer', 'Greenbush', 'Reynolds',
       'Nazareth', 'Hovland', 'Alpharetta', 'Canton', 'Catawba',
       'Scarborough', 'Hopkins', 'Norman Park', 'Sachse', 'Arvada',
       'Winthrop', 'De Soto', 'Sutherland', 'Grandview', 'Manquin',
       'Owensville', 'Altonah', 'Titusville', 'Paris', 'Humble', 'Mounds',
       'Lolita', 'Wetmore', 'Keller', 'Amanda', 'Scotia', 'Pueblo',
       'Purmela', 'Chester Heights', 'Clarks Mills', 'Mount Hope',
       'West Eaton', 'Beaverdam', 'Randolph', 'Greenwich', 'Ragland',
       'Phenix City', 'Coffeeville', 'Stirling', 'Issaquah',
       'Old Hickory', 'West Long Branch', 'Ronceverte', 'Sula',
       'Belle Fourche', 'Vero Beach', 'Curlew', 'Tyler', 'Miamisburg',
       'Providence', 'Saint Louis', 'Duncan', 'De Lancey', 'Lawn',
       'Tryon', 'Milwaukee', 'New Ellenton', 'East Troy', 'Saxon',
       'West Green', 'Atlantic', 'Mc Veytown', 'Ferney', 'Corriganville',
       'Pikesville', 'Cecilton', 'Wheaton', 'Palmdale', 'New Memphis',
       'Newton', 'Valdosta', 'Jordan Valley', 'Edmond', 'Hills',
       'Waupaca', 'Darien', 'Milford', 'De Queen', 'Newberg', 'Plymouth',
       'Columbia', 'Belmont', 'Quanah', 'Barneveld', 'Newark Valley',
       'Downsville', 'American Fork', 'Clifton', 'Stayton', 'Bonfield',
       'Napa', 'West Monroe', 'Dayton', 'Hawley', 'Kingsport', 'Moro',
       'Livonia', 'Sheffield', 'Gretna', 'Haines City', 'Key West',
       'Stanchfield', 'Rockwood', 'Hahira', 'Munith', 'Minnesota Lake',
       'New Waverly', 'Sprague', 'Dieterich', 'Mansfield', 'Winfield',
       'Rochester', 'Oran', 'Orr', 'Crownpoint', 'Putnam', 'San Angelo',
       'Eagarville', 'Leonard', 'Claremont', 'Spencer', 'Nelson',
       'Rockwell', 'Ringwood', 'Oakdale', 'Nokomis', 'Bethel', 'Cedar',
       'Loami', 'Spring Church', 'Brashear', 'Tekoa', 'Kingsville',
       'Galatia', 'Dell City', 'Emmons', 'Norwich', 'Maria Stein',
       'Georgetown', 'Clearwater', 'Albany', 'Indianapolis', 'Red Cliff',
       'Omaha', 'Brooklyn', 'Richland', 'Arnold', 'Odessa', 'Iselin',
       'Washoe Valley', 'Denham Springs', 'Mobile', 'Vanderbilt',
       'Varnell', 'Halma', 'Oriskany Falls', 'Ranier', 'Lawrence',
       'Hurley', 'Grand Bay', 'Sardis', 'Woods Cross', 'Broomfield',
       'Schaumburg', 'Saint Francis', 'Heiskell', 'Unionville',
       'Nobleboro', 'South Hero', 'Carroll', 'Achille', 'Lithopolis',
       'Manley', 'Graniteville', 'Plantersville', 'Jaffrey',
       'Liberty Mills', 'Stephensport', 'Matawan', 'Grantham', 'Tomahawk',
       'Lakeview', 'Lane', 'Pewee Valley', 'Bolton', 'Matthews',
       'Jordanville', 'Syracuse', 'Ruidoso', 'Oak Hill', 'Cressona',
       'Early', 'Bryant', 'Bynum', 'Palermo', 'Fairhope', 'Remer',
       'Baroda', 'Howells', 'Beasley', 'Phil Campbell', 'Deane',
       'North Haverhill', 'Mount Perry', 'Prairie Creek', 'Grand Ridge',
       'Oklahoma City', 'Ashford', 'Huslia', 'Irvine', 'Ehrhardt',
       'Prosperity', 'Dongola', 'Paint Rock', 'Dalton', 'Smock',
       'Bolivar', 'Spring', 'Ridgeland', 'West Finley', 'Lorenzo',
       'Clune', 'Port Costa', 'Oconto Falls', 'Preston', 'Bonita Springs',
       'Hartford', 'Hedrick', 'Boyd', 'Big Indian', 'Cuthbert',
       'Sterling City', 'Queenstown', 'Trenton', 'Kirk', 'Gibsonville',
       'North Brookfield', 'Akron', 'Monitor', 'New Boston', 'Monetta',
       'Mc Intosh', 'Watertown', 'Alton', 'Rock Glen', 'East Rochester',
       'Armonk', 'Stoneham', 'Winslow', 'Williamsburg', 'Mc Clellandtown',
       'Hedley', 'Skytop', 'Cross', 'Deltona', 'Irwinton',
       'North Augusta', 'Collegeville', 'Knowlesville', 'Oakford',
       'Aurora', 'Heislerville', 'Scotts Mills', 'Moscow', 'Williams',
       'Premier', 'Port Charlotte', 'Wendel', 'Harmony',
       'Springfield Gardens', 'North Las Vegas', 'Port Richey',
       'Linthicum Heights', 'Veedersburg', 'Loving', 'Stittville',
       'Kittery Point', 'Greenville', 'Los Angeles', 'Ironton',
       'Vancouver', 'Jackson', 'Kings Bay', 'Thornville', 'Cassatt',
       'Michigan', 'Spirit Lake', 'Pea Ridge', 'West Bethel',
       'New Franken', 'Waukau', 'Crouse', 'Vacaville', 'Madisonville',
       'La Grande', 'Greenport', 'West Frankfort', 'Chattanooga',
       'Gaines', 'Phelps', 'Hubbell', 'Mount Vernon', 'Beacon', 'Clinton',
       'Claypool', 'Walkertown', 'Kaktovik', 'Coulee Dam',
       'Mountain City', 'Granbury', 'Ashland', 'Clarion', 'Downey',
       'Morven', 'Medford', 'Melville', 'Ridge Spring', 'Mineral',
       'Orange Park', 'Norfolk', 'Irvington', 'Oakton', 'Wappapello',
       'Nanuet', 'Seattle', 'Pleasant Hill', 'Karns City', 'North East',
       'Byesville', 'Roland', 'Marshall', 'Isanti', 'Winnsboro',
       'Noblesville', 'Las Vegas', 'Bruce', 'Buellton', 'Grenola',
       'Streator', 'Wartburg', 'East China', 'Brookfield', 'Angwin',
       'Nicholson', 'Lockhart', 'Moss Point', 'Queen Anne', 'Freeport']