artifacts_root: artifacts


data_ingestion:
  root_dir: artifacts/data_ingestion
  source_URL: https://www.kaggle.com/datasets/kartik2112/fraud-detection/download?datasetVersionNumber=1
  local_data_file: artifacts/data_ingestion/data.zip
  unzip_dir: artifacts/data_ingestion/data



preprocessor:
  data_dir: artifacts/data_ingestion/data/fraudTrain.csv
  root_dir: artifacts/preprocessor
  preprocessor_dir: artifacts/preprocessor/preprocessor_obj.pkl


training:
  root_dir: artifacts/training
  trained_model_path: artifacts/training/model.pkl